IOF-14: Merge IOF-14-register-as-volunteer-validation to master
supsign/iofvolunteers pull request #8
Opened 2021-08-13 07:09 UTC by Sil3nce72

Pull request created in: https://supsign.atlassian.net/browse/IOF-14 by the Git Integration for Jira app.

2021-08-13 09:27 UTC, fabcocco requested changes

2021-08-13 09:27 UTC, fabcocco commented on app/Http/Requests/VolunteerRegister.php
> +            'email' => 'required|email|max:191',
Bitte mail besser checken: ich konnte fabrizio@supsign registrieren an dieser Stelle

2021-08-17 20:15 UTC, fabcocco commented on app/Http/Requests/VolunteerRegister.php
> +            'email' => 'required|email|max:191',
@Sil3nce72 dies ist immer noch offen @theKalash magst du supporten und schauen, dass es erledigt wird?

2021-08-18 06:34 UTC, Sil3nce72 commented on app/Http/Requests/VolunteerRegister.php
> +            'email' => 'required|email|max:191',
ich dachte ich hätte das schon gepusht. Dann mach ich das gleich

2021-08-18 06:35 UTC, Sil3nce72 commented on app/Http/Requests/VolunteerRegister.php
> +            'email' => 'required|email|max:191',
Es ist im volunteer-edit drin, aber ich kann es auch auf diesem hier pushen

2021-08-18 08:03 UTC, theKalash approved these changes

2021-08-18 08:05 UTC, fabcocco approved these changes

2021-08-18 08:05 UTC, merged